name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20]

    name: Using Node ${{ matrix.node }} environment

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}
      - run: npm i
      - run: npm run eslint
      - run: npm test
