name: CI 

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.2.0
        with:
          cache: 'npm'
          node-version: '12'
      - run: npm ci
      - run: npm run eslint
      - run: npm test

